### ISSUE TITLE
FC when using as locale/tasker/... plugin

### ISSUE THREAD

**Issue by ppareit** [ppareit/swiftp#115]
From play store review:
The description is shown the ability to start and stop the FTP server from the Tasker (etc .: automagic Lama, e-Robot Automate, ... ).

There is a crash on recent versions of android.

**Comment by ashutoshgngwr** [comment]
Recent as in Android O?

On 29-Dec-2017 10:32 PM, "Pieter Pareit" <notifications@github.com> wrote:

From play store review:
The description is shown the ability to start and stop the FTP server from
the Tasker (etc .: automagic Lama, e-Robot Automate, ... ).

There is a crash on recent versions of android.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ppareit/swiftp/issues/115>, or mute the thread

**Comment by ppareit** [comment]
Probably earlier. I currently only have tested this on android 8.1.0. Might have been because newer versions of libraries.
Inheriting from AbstractAppCompatPluginActivity and using getSupportActionBar() solves this. Alternative was testing for null pointer but then we could not set title correct.

**Comment by ashutoshgngwr** [comment]
I will look into it!

On 29-Dec-2017 10:40 PM, "Pieter Pareit" <notifications@github.com> wrote:

Probably earlier. I currently only have tested this on android 8.1.0. Might
have been because newer versions of libraries.
Inheriting from AbstractAppCompatPluginActivity and using
getSupportActionBar() solves this. Alternative was testing for null pointer
but then we could not set title correct.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ppareit/swiftp/issues/115#issuecomment-354473000>, or mute
the thread

**Comment by ppareit** [comment]
Cool, also see this commit:
https://github.com/ppareit/swiftp/commit/054af681412ea0868dcb0c1c64d8294ea81ba98f

**Comment by ashutoshgngwr** [comment]
Didn't see that coming! LOL

**Comment by swiftSwathSee** [comment]
Still crashes for me on Android 4.4.2.
