### ISSUE TITLE
File rename: false positive message  if target filename exists

### ISSUE THREAD

**Issue by Vrihub** [ppareit/swiftp#232]
If you run a RNTO command using the name of an already existing file, ftpserver replies with "250 rename successful" but in fact no files are modified.

Thiugh I'm not sure how RNTO should behave in this case, overwrite the target file or throw an error message, the current message is misleading.

**Comment by Xavron** [comment]
Is this with File or scoped storage aka enabled "write external storage" in settings? File is used when write external storage is disabled.

- If its with File, then it would be unfixed for sure.

- If its with "write external storage" enabled by building from source, then you'd need https://github.com/ppareit/swiftp/pull/205 applied where it would be fixed. I'd recommend applied on top of that https://github.com/ppareit/swiftp/pull/217

- If its with the apk (f-driod, Play Store) then you'd need to build from source at this time for the fix for this.

So, technically its fixed already. But, your use can see older based problems where things aren't fixed based on how you do things or use the app.

**Comment by Vrihub** [comment]
Thanks for the detailed answer and sorry for not providing much detail.

I'm using the latest fdroid apk and "writing external storage" is enabled, though I experienced the problem trying to rename a file on the internal storage (not the external sd card, if that is relevant).

Anyway I can live with that, I'll just wait for the fix to be distributed and for now I'll make sure to remove files instead of overwriting them. Thanks again!

**Comment by Xavron** [comment]
No prob. Its all good :)
