### ISSUE TITLE
What happened to the free/demo version?

### ISSUE THREAD

**Issue by krt16s** [ppareit/swiftp#76]
Could you re-add the demo/free version, e.g. by using gradle build flavors? Or is it okay, if we at F-Droid build from this source directly (and append `_free` to the package id)?

**Comment by mvdan** [comment]
Just for completeness, another option is for us to drop `*.switftp_free` in favour of `*.swiftp`. Although that will leave users of the former without updates, since it will be a different app.

**Comment by ppareit** [comment]
@krt16s Since the move from eclipse to android studio the free version has not been updated. This must be remedied! I should have enough time tomorrow to make a gradle build flavor and test.

@mvdan I prefer to keep the name `.swiftp_free`. This keeps a large group of users updated (> 5000). As important is that the name of the free version may not clash with the name of the paid version. This could even give problems with the play store as the apk name and the apk keys are checked.

I'll update this issue more tomorrow.

**Comment by mvdan** [comment]
Okay then. I was thinking that perhaps the two versions were collapsing into one.

**Comment by ppareit** [comment]
@krt16s for fdroid there has been added a build variant `fdroid_free`, you will thus need `fdroid_freeRelease` for building. I've just tested building the demo version, an other build variant. I'll keep this open till you have been able to release. If everything goes well, I'll keep the tags back updated on github and you should be able to release in sync with me.

**Comment by ppareit** [comment]
Closed because the fdroid version is now in sync. Thanks!
